export const products = [
    {
        id: 1,
        sku: "CLI00001",
        name: "Xbox Series S - 512GB SSD Console with Wireless Controller - EU Version",
        brand: "Xbox",
        image: "https://clicon-web-api.vercel.app/products/ps5.png",
        price: 865.99,
        discountedPrice: 442.12,
        ratings: 4.7,
        isFreeShipping: true,
        isBestDeal: true,
        isFeatured: false,
        category: "game",
        subCategory: "",
        description: "Games built using the Xbox Series X|S development kit showcase unparalleled load times, visuals..",
        availability: true,
        stockCount: 50,
        promotion: ["off", "hot"],
        discountPercentage: 30,
    },
    {
        id: 2,
        sku: "CLI00002",
        name: "Bose Sport Earbuds",
        brand: "Bose",
        image: "https://clicon-web-api.vercel.app/products/product-1.png",
        price: 567.89, 
        ratings: 5,
        isFreeShipping: true,
        isBestDeal: true,
        isFeatured: false,
        category: "gadgets",
        subCategory: "",
        description: "Bose Sport Earbuds - Wireless Earphones - Bluetooth In Ear...",
        availability: false,
        stockCount: 0,
        promotion: ["sold out"],
        discountPercentage: 0
    },
    {
        id: 3,
        sku: "CLI00003",
        name: "Simple Mobile 4G LTE Prepaid Smartphone",
        brand: "Samsung",
        image: "https://clicon-web-api.vercel.app/products/product-2.png",  
        price: 865.99,
        discountedPrice: 654.52, 
        ratings: 3.8,
        isFreeShipping: true,
        isBestDeal: true,
        isFeatured: false,
        category: "smartphone",
        subCategory: "",
        description: "Simple Mobile 4G LTE Prepaid Smartphone",
        availability: true,
        stockCount: 35, 
        promotion: ["off"],
        discountPercentage: 20
    },
    {
        id: 4,
        sku: "CLI00004",
        name: "4K UHD LED Game Console",
        brand: "UHD",
        image: "https://clicon-web-api.vercel.app/products/product-3.png",
        price: 550.25, 
        ratings: 4.5,
        isFreeShipping: true,
        isBestDeal: true,
        isFeatured: false,
        category: "game",
        subCategory: "consoles",
        description: "4K UHD LED Game Console with Chromecast Built-in",
        availability: true,
        stockCount: 55,
        discountPercentage: 0,
    },
    {
        id: 5,
        sku: "CLI00005",
        name: "Sony DSCHX8 High Zoom Point & Shoot Camera",
        brand: "Sony",
        image: "https://clicon-web-api.vercel.app/products/product-4.png",
        price: 438.44, 
        ratings: 4.2,
        isFreeShipping: true,
        isBestDeal: true,
        isFeatured: false,
        category: "camera",
        subCategory: "",
        description: "Sony DSCHX8 High Zoom Point & Shoot Camera",
        availability: true,
        stockCount: 41,
        discountPercentage: 0, 
    },
    {
        id: 6,
        sku: "CLI00006",
        name: "Dell Optiplex",
        brand: "Dell",
        image: "https://clicon-web-api.vercel.app/products/product-5.png",
        price: 597.92, 
        ratings: 3.7,
        isFreeShipping: true,
        isBestDeal: true,
        isFeatured: false,
        category: "smartphone",
        subCategory: "",
        description: "Dell Optiplex 7000x7480 All-in-One Computer Monitor",
        availability: true,
        stockCount: 26, 
        discountPercentage: 0, 
    },
    {
        id: 7,
        sku: "CLI00007",
        name: "Portable Washing Machine",
        brand: "Whirlpool",
        image: "https://clicon-web-api.vercel.app/products/product-6.png",
        price: 482.33,
        discountedPrice: 385.42, 
        ratings: 4.3,
        isFreeShipping: true,
        isBestDeal: true,
        isFeatured: false,
        category: "electronics",
        subCategory: "washing machine",
        description: "Portable Washing Machine, 11lbs capacity Model 18NMFIAM",
        availability: true,
        stockCount: 34, 
        promotion: ["hot"],
        discountPercentage: 15, 
    },
    {
        id: 8,
        sku: "CLI00008",
        name: "Netflix TV Show",
        brand: "Netflix",
        image: "https://clicon-web-api.vercel.app/products/product-7.png", 
        price: 555.22,
        ratings: 3.4,
        isFreeShipping: true,
        isBestDeal: true,
        isFeatured: false,
        category: "tv",
        subCategory: "leisure",
        description: "2-Barrel Carburetor Carb 2100 Engine Increase Horsepower",
        availability: true,
        stockCount: 50,   
        discountPercentage: 0, 
    },
    {
        id: 9,
        sku: "CLI00009",
        name: "3-Barrel Carburetor Carb",
        brand: "Barrel",
        image: "https://clicon-web-api.vercel.app/products/product-8.png",
        price: 624.53,
        discountedPrice: 535.87,
        ratings: 4.4,
        isFreeShipping: true,
        isBestDeal: true,
        isFeatured: false,
        category: "camera",
        subCategory: "webcam",
        description: "2-Barrel Carburetor Carb 2100 Engine Increase Horsepower",
        availability: true,
        stockCount: 50,
        promotion: ["off"],
        discountPercentage: 12,
    },
    {
        id: 10,
        sku: "CLI00010",
        name: "TOZO T6 True Wireless Earbuds Bluetooth Headphone",
        brand: "TOZO",
        image: "https://clicon-web-api.vercel.app/products/product-15.png",
        price: 300.25, 
        ratings: 3.8,
        isFreeShipping: true,
        isBestDeal: false,
        isFeatured: true,
        category: "electronics",
        subCategory: "headphone",
        description: "TOZO T6 True Wireless Earbuds Bluetooth Headphone",
        availability: true,
        stockCount: 44, 
        promotion: ["hot"],
        discountPercentage: 0,  
    },
    {
        id: 11,
        sku: "CLI00011",
        name: "Samsung Electronics Samsung Galaxy S21 5G",
        brand: "Samsung Galaxy",
        image: "https://clicon-web-api.vercel.app/products/product-16.png",
        price: 300.25, 
        ratings: 4.6,
        isFreeShipping: true,
        isBestDeal: false,
        isFeatured: true,
        category: "electronics",
        subCategory: "smartphone",
        description: "Samsung Electronics Samsung Galexy S21 5G",
        availability: true,
        stockCount: 37, 
        discountPercentage: 0,  
    },
    {
        id: 12,
        sku: "CLI00012",
        name: "DELL Air Conditioner",
        brand: "DELL",
        image: "https://clicon-web-api.vercel.app/products/product-17.png",
        price: 304.25, 
        ratings: 4.6,
        isFreeShipping: true,
        isBestDeal: false,
        isFeatured: true,
        category: "electronics",
        subCategory: "air-conditioner",
        description: "High-Speed Air Conditioner",
        availability: true,
        stockCount: 50,
        promotion: ["best deals"],
        discountPercentage: 0
    },
    {
        id: 13,
        sku: "CLI00013",
        name: "Amazon Basics Washing Machine with 11lbs capacity Model 18NMF",
        brand: "Amazon",
        image: "https://clicon-web-api.vercel.app/products/product-18.png",
        price: 700.25, 
        ratings: 3.9,
        isFreeShipping: true,
        isBestDeal: false,
        isFeatured: true,
        category: "accessories",
        subCategory: "",
        description: "Portable Washing Machine, 11lbs capacity Model 18NMF...",
        availability: true,
        stockCount: 50, 
        promotion: [],
        discountPercentage: 0 
    },
]